name-template: v$NEXT_PATCH_VERSION
tag-template: v$NEXT_PATCH_VERSION
template: |
    # What's Changed
    $CHANGES
categories:
  - title: 🚀 Features
    labels:
      - feature
      - type/feature
  - title: ⚠️ Breaking Changes
    labels:
      - breaking change
      - type/bc-break
  - title: 🐛 Bug Fixes
    labels:
      - bug
      - type/bug
  - title: 📖 Documentation
    labels:
      - documentation
      - type/docs
  - title: 🧹 Housekeeping
    labels:
      - chore
      - test flakiness
      - type/housekeeping
      - type/test-flakiness
      - type/test-improvement
  - title: 📦 Dependency updates
    label: dependencies
